alias sudo='sudo '
alias nohup='nohup '
alias cat='bat'
alias sl='lsd'
alias ls='lsd'
alias la='lsd -Ah'
alias ll='lsd -Ah -l'
alias li='lsd -Ah -l -i'
alias l='ll'
alias lvim='lvim -O'
alias nvim='lvim -O'
alias vim='nvim'
alias vi='nvim'
alias v='nvim'
alias vimdiff='nvim -d'
alias ip='ip --color=auto'
alias diff='diff --color=auto'
alias grep='grep --color=auto'
alias pacman='pacman --color=auto'
alias yay='yay --color=auto'
alias tree='tree --gitignore -I .git -C'
alias less='less -iR'
alias d='dirs -v'

for index ({1..9}) alias "$index"="cd +$index"; unset index
