# Set the width of a tab to 4 spaces.
tabs -4

setopt AUTO_CD
setopt AUTO_PUSHD
setopt PUSHD_IGNORE_DUPS
setopt PUSHD_SILENT
# setopt ALWAYS_TO_END
# setopt COMPLETE_IN_WORD
setopt MENU_COMPLETE
setopt GLOB_STAR_SHORT
setopt EXTENDED_HISTORY
setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_SAVE_NO_DUPS
setopt HIST_VERIFY
setopt SHARE_HISTORY
setopt NO_FLOW_CONTROL
setopt INTERACTIVE_COMMENTS
setopt PROMPT_SUBST
# setopt TRANSIENT_RPROMPT
