[alias]
  a     = add
  aa    = add --all
  ap    = add --patch
  b     = branch
  ba    = branch --all
  bm    = branch --move
  br    = branch --remote
  c     = commit
  ca    = commit --amend
  cam   = commit --amend --message
  cane  = commit --ammend --no-edit
  cl    = clone
  clrsm = clone --recurse-submodules
  cm    = commit --message
  co    = checkout
  cob   = checkout --branch
  cp    = cherry-pick
  cpa   = cherry-pick --abort
  cpc   = cherry-pick --continue
  d     = diff
  ds    = diff --staged
  f     = fetch
  g     = grep
  l     = log
  la    = log --all
  lg    = log --graph
  ll    = log --graph --all --decorate --oneline
  lll   = log --graph --all --decorate
  lo    = log --oneline
  lor   = log --oneline --reverse
  ls    = ls-files
  lsfn  = ls-files --full-name
  m     = merge
  ma    = merge --abort
  mc    = merge --continue
  pl    = pull
  plf   = pull --ff-only
  plr   = pull --rebase
  ps    = push
  rb    = rebase
  rba   = rebase --abort
  rbc   = rebase --continue
  rbi   = rebase --interactive
  rbs   = rebase --skip
  rl    = reflog
  rr    = remote
  rs    = restore
  rsp   = restore --patch
  rss   = restore --staged
  rssp  = restore --staged --patch
  rv    = revert
  s     = status
  sm    = submodule
  sma   = submodule add
  smi   = submodule init
  sms   = submodule sync
  smu   = submodule update
  smui  = submodule update --init
  smuir = submodule update --init --recursive
  st    = stash
  sta   = stash apply
  stl   = stash list
  stp   = stash pop
  stps  = stash push
  stpsa = stash push --all
  stpsu = stash push --include-untracked
  sts   = stash show
  stsp  = stash show --patch
  w     = whatchanged
