[general]
import = ["~/.config/alacritty/alacritty-theme/themes/citylights.toml"]
ipc_socket = true
live_config_reload = true

[window]
decorations = "None"
dynamic_padding = true
opacity = 0.95
padding = { x = 5, y = 5 }
startup_mode = "Maximized"

[scrolling]
history = 10000
multiplier = 3

[font]
bold = { family = "Hurmit Nerd Font", style = "Bold" }
bold_italic = { family = "Hurmit Nerd Font", style = "Bold Italic" }
italic = { family = "Hurmit Nerd Font", style = "Italic" }
normal = { family = "Hurmit Nerd Font", style = "Regular" }
size = 11

[colors]
transparent_background_colors = true

[mouse]
hide_when_typing = true
